Running cluster for deep fits
120108 120109 normal
Running object 120108
Not enough g observations!
WARNING: Could not memory map array with mode='readonly', falling back to mode='denywrite', which means that the array will be read-only [astropy.io.fits.file]
Min gap is: 0.00390625
New time_gap is :0.00790625
Number of observations now:  16
Min gap is: 0.00390625
New time_gap is :0.00790625
Number of observations now:  50
Min gap is: 0.00390625
New time_gap is :0.00790625
Number of observations now:  122
Counts: {'r': 16, 'i': 46, 'z': 113}
Mu: {'g': 0.0, 'r': 0.15554853, 'i': 0.23622687, 'z': 0.39675713}
No handles with labels found to put in legend.
Variable??
0
0
Non-Variable source in g
Variable??
0.028328225016593933
4.521788751962191
Variable Source in r!!
Variable??
0.0410440995830577
1.3356244565600706
Non-Variable source in i
Variable??
0.06328728640602217
1.473576587345023
Non-Variable source in z
Variable:    1/4
Var Bands:   r
Slope:       [1, 1, 1, 1]
Slope Error: [0.0, 0, 0.21322110323328908, 0.08964311811183452]
intercepts:  [0, 0, 0.11511494199295233, 0.03909713891315876]
Int Error:   [0.0, 0, 0.19656393705468314, 0.08366153640496869]
StDev:       [0.0, 0.13125466, 0.14483881, 0.103032626]
Spread:      1/4
Spread values: 
I 0.041478746
ROW: 120108all Tau: 0.010828931759707672 V: -0.7764816667281068
ClusterEmcee2_linear_mu_all_and_single_fast.py:643: RuntimeWarning: divide by zero encountered in log10
  mu_list = [22.5-2.5*np.log10(mu[i]) for i in mu]
ROW: 120108r Tau: 1.715661857444096 V: -0.43251659300669343
Close extra plots
Row 120108 ran in 8.7223 seconds
Successfully finished!
Rows 120108 to 120109 ran in 11.1916 seconds
